# Generated by Django 4.0 on 2022-03-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
